spring:
  rabbitmq:
    host: rabbitmq-service.default.svc.cluster.local
    password: guest
    port: 5672
    username: guest
    exchange: movie.exchange
    queue: movie.queue
    routingkey: movie.routingkey